site_name: MakerLab Guide
site_url: https://mydomain.org/mysite
theme:
  name: material
  language: en 
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.indexes # Have index.md be the linked to by the folder, not a page within it.
    - toc.follow 
  palette:
    # Palette toggle for light mode
    - scheme: makerlab-light
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: makerlab-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# To have it automatically construct the nav, you can simply omit this entire section.
# Important notes: For paths, make sure you use a forward slash "/", a backslash "\" will work on windows, but not on the linux server deploying this.
# ALWAYS USE FORWARD SLASH "/"
nav:
  - index.md 
  - get_connected.md
  - Available Tools:
    - Available Tools/index.md
    - Available Tools/laser_cutter.md
  - Policies:
    - Policies/index.md
    - Policies/lost_and_found.md
    - Policies/bic_kic_access.md
  - makerlab_classes.md
  - current_officers.md
  - FAQ.md
  - officer_weekly_meetings.md
  - about_makerlab.md
  - Constitution:
    - MakerLab Constitution/index.md
    - MakerLab Constitution/active_constitution.md
  - Public Documents:
    - Public Documents/index.md
    - Public Documents/project_slip_printout.md
  - Editing Website:
    - Editing This Website/index.md
    - Editing This Website/Who Can Edit.md
    - Editing This Website/Instructions.md

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mermaid2:
      version: 10.0.2


extra_css:
  - stylesheets/color_schemes.css

#copyright: Copyright &copy; 2025 MakerLab
extra:
  generator: true # The little Generated by MkDocs text in the footer
  
  social:
    # Available icons can be seen here: https://fontawesome.com/search?ip=brands&o=r
    - icon: fontawesome/brands/discord
      link: http://discord.gg/tzBHVw2
      name: Join MakerLab Discord

    - icon: material/calendar-today
      link: https://rosehulman.campusgroups.com/feeds?type=club&type_id=35475&tab=about
      name: Join CampusGroups

    - icon: fontawesome/brands/github
      link: https://github.com/orgs/Rose-MakerLab
      name: See MakerLab GitHub Organization


markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  - pymdownx.superfences:
      # This uses the plugin to interpret mermaid blocks because we are not insiders for the built-in implementation.
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde